/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  STAFF: 'STAFF',
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const Status = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  DELETED: 'DELETED',
} as const;

export type Status = (typeof Status)[keyof typeof Status];

export const SchoolType = {
  HIGH: 'HIGH',
  SECONDARY: 'SECONDARY',
} as const;

export type SchoolType = (typeof SchoolType)[keyof typeof SchoolType];

export const CurriculumComponentKind = {
  MAJOR: 'MAJOR',
  ELECTIVE: 'ELECTIVE',
} as const;

export type CurriculumComponentKind = (typeof CurriculumComponentKind)[keyof typeof CurriculumComponentKind];
